export const issues = [
  { number: 1, label: 'Label niet gekoppeld aan invoer' },
  { number: 2, label: 'Vragen om invoer te herhalen' },
  { number: 3, label: 'Haakje(s) voor afkorting(en)' },
  { number: 4, label: 'Taalgebruik niet consistent' },
  { number: 5, label: 'Invoerfout alleen met kleur aangegeven' },
  { number: 6, label: 'Vragen om onnodige informatie' },
  { number: 7, label: 'Invoer zoals naam of e-mail adres zonder autocomplete' },
  { number: 8, label: 'Alle tekstvelden zijn even lang' },
  { number: 9, label: 'Tekstvelden in kolommen' },
  { number: 10, label: 'Foutmelding zichtbaar voor je klaar bent met invoeren' },
  { number: 11, label: 'Geen uitleg waar privé gegevens voor nodig zijn' },
  { number: 12, label: 'Je kunt niet met je toetsenbord door het formulier' },
  { number: 13, label: 'Focus van tabtoets navigatie niet zichtbaar' },
  { number: 14, label: 'Labels voor de invoervelden in plaats van erboven' },
  { number: 15, label: 'Knoppen staan aan het eind van de regel' },
  { number: 16, label: 'Moeilijke afkortingen en jargon worden niet uitgelegd' },
  { number: 17, label: 'Belangrijke informatie in tooltip of placeholder' },
  { number: 18, label: 'Overenthousiaste validatie op bijvoorbeeld naam, postcode of e-mailadres' },
  { number: 19, label: 'Vertaalplugins zoals Google Translate vertalen ook invoer zoals naam en straatnaam' },
  { number: 20, label: 'Naam van formulier of formulier stap staat niet in de browser tab of geschiedenis' },
  { number: 21, label: 'Onduidelijke of herhaaldelijk gebruikte invoerfoutmelding' },
  { number: 22, label: 'Gebruik van "select" component bij minder dan 6 opties' },
  { number: 23, label: 'Maximale lengte van invoer gebaseerd op gemiddelde lengte niet uitzonderlijke lengte' },
  { number: 24, label: '"Annuleren", "Opslaan" en "Versturen" knoppen zien er precies hetzelfde uit' },
  { number: 25, label: 'Gebruik van allemaal kapitalen in kopjes of knoppen' },
  { number: 26, label: 'Verschil tussen verplichte en optionele invoervelden alleen aangegeven met astrisk' },
];
