export const issues = [
  { number: 1, label: 'Label niet gekoppeld aan invoer' },
  { number: 2, label: 'Vragen om invoer te herhalen' },
  { number: 3, label: 'Haakje(s) voor afkorting(en)' },
  { number: 4, label: 'Taalgebruik niet consistent' },
  { number: 5, label: 'Invoerfout alleen met kleur aangegeven' },
  { number: 6, label: 'Vragen om onnodige informatie' },
  { number: 7, label: 'Geen gebruik van autocomplete ondersteuning' },
  { number: 8, label: 'Alle tekstvelden zijn even lang' },
  { number: 9, label: 'Tekstvelden in kolommen of in een tabel' },
  { number: 10, label: 'Foutmelding voor je klaar bent met invoeren' },
  { number: 11, label: 'Geen uitleg waar privé gegevens voor nodig zijn' },
  { number: 12, label: 'Je kunt niet met je toetsenbord door het formulier' },
  { number: 13, label: 'Focus van tabtoets navigatie niet zichtbaar' },
  { number: 14, label: 'Knoppen staan aan het eind van de regel' },
  { number: 15, label: 'Afkortingen en jargon worden niet uitgelegd' },
  { number: 16, label: 'Belangrijke informatie in tooltip of placeholder' },
  { number: 17, label: 'Geldige invoer is afgekeurd' },
  { number: 18, label: 'Invoer moet per se mét of zónder spatie' },
  { number: 19, label: 'Contactgegevens worden niet vooraf ingevuld met DigiD' },
  { number: 20, label: 'Vertaal software vertaald invoer op de controlepagina' },
  { number: 21, label: 'Foutmelding is niet aan het formulierveld gekoppeld' },
  { number: 22, label: 'Foutmelding helpt niet om de vraag juist in te vullen' },
  { number: 23, label: 'Onduidelijk welke velden verplicht ingevuld moeten worden' },
  { number: 24, label: 'Labels of beschrijvingen slecht leesbaar' },
];
